### ISSUE TITLE
/thx コマンドのパラメータとして指定するのに適切なのは、ユーザー表示名なのか、ユーザー名なのか？

### ISSUE THREAD

**Issue by takagishun** [sashiyama/thx#10]

**Comment by sashiyama** [comment]
@takagishun 
ユーザ表示名はユニークではないと思うので、ユーザ名にしたいです。
それともユーザ表示名もユニーク？

**Comment by takagishun** [comment]
@sashiyama 
取り敢えずユーザ名にしますか。

**Comment by takagishun** [comment]
@sashiyama 
表示名もユニークっぽいのと、
送りやすいので表示名で指定する方法で進めます。

**Comment by sashiyama** [comment]
ユーザIDを取得できたのでclose
